/**
 * @author lsz
 * @type {Object}
 * @desc 全局事件定义,定义规则: FILENAME_[CUSTOM NAME]_EVENT  eg: B_EVENT,  B_CLICK_EVENT
 *       *事件名后加上说明
 */
export const events = {
  LOGIN_EVENT: 'LOGIN_EVENT',
  WINDOW_CHANGE_EVENT: 'WINDOW-CHANGE-EVENT', // 窗口大小改变
  MENU_SWITCH_EVENT: 'MENU_SWITCH_EVENT', // 菜单开关
  POPUP_WIN_EVENT: 'POPUP_WIN_EVENT', // 弹出窗口
  POPDOWN_WIN_EVENT: 'POPDOWN_WIN_EVENT', // 关闭窗口
  REGION_SELECT_EVENT: 'REGION_SELECT_EVENT', // 综合保障情况地市选择
  AREA_SELECT_EVENT: 'AREA_SELECT_EVENT', // 自定义场景区域选择
  BTS_MAP_POINT_EVENT: 'BTS_MAP_POINT_EVENT', // 基站搜索地图打点
  CHANGE_MAP_RENDER_EVENT: 'CHANGE_MAP_RENDER_EVENT', // 网络概览-->改变地图渲染
  MAP_LAYERY_OPT_EVENT: 'MAP_LAYERY_OPT_EVENT', // 地图打点(清除图层&添加图层)
  REPORT_MAP_LAYER_EVENT: 'REPORT_MAP_LAYER_EVENT', // 应急汇报打点
  REPORT_MAP_LAYER_CHANGE: 'REPORT_MAP_LAYER_CHANGE', // 应急汇报切换图层
  SCENESAFE_CHANGE_DATA_EVENT: 'SCENESAFE_CHANGE_DATA_EVENT', // 重点保障-->改变地图渲染及故障、性能信息, 公共图层
  SCENESAFE_CUSTOM_DATA_EVENT: 'SCENESAFE_CUSTOM_DATA_EVENT', // 重点保障-->故障图层，性能恶化图层
  SCENESAFE_FAULT_DATA_EVENT: 'SCENESAFE_FAULT_DATA_EVENT', // 重点保障-->故障区域鼓掌信息
  WEATHER_CUSTOM_DATA_EVENT: 'WEATHER_CUSTOM_DATA_EVENT', // 天气实况
  WEATHER_CUSTOM_MAP_EVENT: 'WEATHER_CUSTOM_MAP_EVENT', // 天气实况.地图打点
  MARKER_CLICK_EVENT: 'MARKER_CLICK_EVENT', // POPUP弹窗
  PUBLICLAYER_SELECT_EVENT: 'PUBLICLAYER_SELECT_EVENT', // 公共图层
  PUBLICLAYER_TRAIL_BTS_EVENT: 'PUBLICLAYER_TRAIL_BTS_EVENT', // 轨迹描绘，对应基站
  // 格式:PUBLICLAYER + 图层ID + EVENT
  PUBLICLAYER_L1003_EVENT: 'PUBLICLAYER_L1003_EVENT', // 公共图层:抢修车
  PUBLICLAYER_L1004_EVENT: 'PUBLICLAYER_L1004_EVENT', // 公共图层：应急车
  PUBLICLAYER_L1005_EVENT: 'PUBLICLAYER_L1005_EVENT', // 公共图层：油机车
  PUBLICLAYER_L1006_EVENT: 'PUBLICLAYER_L1006_EVENT', // 公共图层：无线队伍
  PUBLICLAYER_L1007_EVENT: 'PUBLICLAYER_L1007_EVENT', // 公共图层：传输队伍
  PUBLICLAYER_L1008_EVENT: 'PUBLICLAYER_L1008_EVENT', // 公共图层：卫星电话
  PUBLICLAYER_L1009_EVENT: 'PUBLICLAYER_L1009_EVENT', // 公共图层：信息回传
  PUBLICLAYER_L1010_EVENT: 'PUBLICLAYER_L1010_EVENT', // 公共图层：GSM退服基站
  PUBLICLAYER_L1011_EVENT: 'PUBLICLAYER_L1011_EVENT', // 公共图层：TD退服基站
  PUBLICLAYER_L1012_EVENT: 'PUBLICLAYER_L1012_EVENT', // 公共图层：LTE退服基站
  PUBLICLAYER_L1014_EVENT: 'PUBLICLAYER_L1014_EVENT', // 公共图层：台风
  TYPHOON_EVENT: 'TYPHOON_EVENT',
  TYPHOON_BTS_EVENT: 'TYPHOON_BTS_EVENT', // 台风影响基站
  TRANS_MAP_OPT_EVENT: 'TRANS_MAP_OPT_EVENT', // 传输故障地图操作
  UPDATE_FORECAST_COUNTRY_EVENT: 'UPDATE_FORECAST_COUNTRY_EVENT', // 修改台风预测国家
  TRANSALRAM_MAP_EVENT: 'TRANSALRAM_MAP_EVENT', // 应急场景-传输故障 tr td 地图打点
  TRAINING_RMG_EVENT: 'TRAINING_RMG_EVENT', // 应急拉练
  BTS_SEARCH_OPT_EVENT: 'BTS_SEARCH_OPT_EVENT', // 应急调度 基站搜索
  ADD_CUSTOM_SCENE_EVENT: 'ADD_CUSTOM_SCENE_EVENT' // 自定义框选场景
}
